name: CD

on:
  # Triggers the workflow on push on master branch
  push:
    branches: [ master ]
  workflow_run:
    workflows: ["CI"]


jobs:

  deploy:
    needs: build
    runs-on: ubuntu-latest 
   
    steps:
      - uses: actions/checkout@v2

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: 'v1.12.3'
          kubernetes version: 'v1.18.3'

      - name: Try the cluster !
        run: kubectl get pods -A

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Deploy Terraform to minikube
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Test service URLs
        run: |
          sleep 10s
          minikube service list
          minikube service myservice --url
          echo "------------------opening the service------------------"
          curl $(minikube service myservice --url) 
