# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest 
   
    steps:
      - uses: actions/checkout@v2

      - name: Test merge
        if: github.event.pull_request.merged == true
        run: echo "ok"

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: 'v1.12.3'
          kubernetes version: 'v1.18.3'

      - name: Try the cluster !
        run: kubectl get pods -A

      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          pwd
          ls
          docker build -f ./Dockerfile -t simpledocker:v1 .
          echo -n "verifying local docker images:"
          docker images

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Deploy Terraform to minikube
        working-directory: ./terraform
        # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve

      - name: Test service URLs
        if: github.event.pull_request.merged == true
        run: |
          sleep 10s
          minikube service list
          minikube service myservice --url
          echo "------------------opening the service------------------"
          curl $(minikube service myservice --url) 

