# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # build:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v2

  #     # Build docker image
  #     - name: Build docker
  #       run: docker build . --file Dockerfile --tag simpledocker:v1

  #     - name: Run container
  #       run: docker run -d -p 80:80 simpledocker:v1
    
  #     - name: Check http status code
  #       run: curl http://127.0.0.1:80

  deploy:
    runs-on: ubuntu-latest 
    # if: github.event.pull_request.merged == 'true'
   
    steps:
      - uses: actions/checkout@v2

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Try the cluster !
        run: kubectl get pods -A

      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          pwd
          ls
          docker build -f ./Dockerfile -t simpledocker:v1 .
          echo -n "verifying images:"
          docker images

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Deploy Terraform to minikube
        working-directory: ./terraform
        # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve

      - name: Test service URLs
        run: |
          minikube service list
          minikube service example --url
          echo "------------------opening the service------------------"
          curl $(minikube service example --url) 