# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        id:   docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: linouche5/public-repo:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Image test
        run: |
          docker images
          docker run -d -p 8080:80 linouche5/public-repo:latest
          sleep 5s
          curl http://127.0.0.1:8080 
          ./test.sh http://127.0.0.1:8080   


  deploy:
    needs: build
    runs-on: ubuntu-latest 
   
    steps:
      - uses: actions/checkout@v2

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: 'v1.12.3'
          kubernetes version: 'v1.18.3'

      - name: Try the cluster !
        run: kubectl get pods -A

      # - name: Build image
      #   run: |
      #     export SHELL=/bin/bash
      #     eval $(minikube -p minikube docker-env)
      #     pwd
      #     ls
      #     docker build -f ./Dockerfile -t simpledocker:v1 .
      #     echo -n "verifying local docker images:"
      #     docker images

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Deploy Terraform to minikube
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Test service URLs
        run: |
          sleep 10s
          minikube service list
          minikube service myservice --url
          echo "------------------opening the service------------------"
          curl $(minikube service myservice --url) 

